[2024-01-01T17:10:04.673+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2024-01-01T17:10:04.684+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2024-01-01T17:10:04.684+0100] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2024-01-01T17:10:04.695+0100] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): third_task> on 2023-09-30 00:00:00+00:00
[2024-01-01T17:10:04.698+0100] {standard_task_runner.py:57} INFO - Started process 73694 to run task
[2024-01-01T17:10:04.704+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v4', 'third_task', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '13112', '--raw', '--subdir', '/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/methode-1/dags/our_first_dag.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmp_0ikies3']
[2024-01-01T17:10:04.707+0100] {standard_task_runner.py:85} INFO - Job 13112: Subtask third_task
[2024-01-01T17:10:04.759+0100] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v4.third_task scheduled__2023-09-30T00:00:00+00:00 [running]> on host macbook-pro-de-user.local
[2024-01-01T17:10:05.278+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2024-01-01T17:10:05.279+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2024-01-01T17:10:05.280+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'I am task 3 and I will be running after the task 2!']
[2024-01-01T17:10:05.288+0100] {subprocess.py:86} INFO - Output:
[2024-01-01T17:10:05.290+0100] {subprocess.py:93} INFO - /bin/bash: I: command not found
[2024-01-01T17:10:05.291+0100] {subprocess.py:97} INFO - Command exited with return code 127
[2024-01-01T17:10:05.301+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/py_env/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-01-01T17:10:05.305+0100] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=our_first_dag_v4, task_id=third_task, execution_date=20230930T000000, start_date=20240101T161004, end_date=20240101T161005
[2024-01-01T17:10:05.315+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 13112 for task third_task (Bash command failed. The command returned a non-zero exit code 127.; 73694)
[2024-01-01T17:10:05.363+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-01T17:10:05.378+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
