[2023-12-28T19:37:37.337+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2021-12-29T00:00:00+00:00 [queued]>
[2023-12-28T19:37:37.344+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2021-12-29T00:00:00+00:00 [queued]>
[2023-12-28T19:37:37.344+0100] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2023-12-28T19:37:37.356+0100] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): third_task> on 2021-12-29 00:00:00+00:00
[2023-12-28T19:37:37.358+0100] {standard_task_runner.py:57} INFO - Started process 28516 to run task
[2023-12-28T19:37:37.365+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v4', 'third_task', 'scheduled__2021-12-29T00:00:00+00:00', '--job-id', '2786', '--raw', '--subdir', '/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/methode-1/dags/our_first_dag.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmp8smwc4jb']
[2023-12-28T19:37:37.368+0100] {standard_task_runner.py:85} INFO - Job 2786: Subtask third_task
[2023-12-28T19:37:37.420+0100] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v4.third_task scheduled__2021-12-29T00:00:00+00:00 [running]> on host macbook-pro-de-user.local
[2023-12-28T19:37:37.917+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2021-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-29T00:00:00+00:00'
[2023-12-28T19:37:37.918+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2023-12-28T19:37:37.919+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'I am task 3 and I will be running after the task 2!']
[2023-12-28T19:37:37.930+0100] {subprocess.py:86} INFO - Output:
[2023-12-28T19:37:37.936+0100] {subprocess.py:93} INFO - /bin/bash: I: command not found
[2023-12-28T19:37:37.937+0100] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-28T19:37:37.947+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/py_env/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-28T19:37:37.952+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v4, task_id=third_task, execution_date=20211229T000000, start_date=20231228T183737, end_date=20231228T183737
[2023-12-28T19:37:37.963+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 2786 for task third_task (Bash command failed. The command returned a non-zero exit code 127.; 28516)
[2023-12-28T19:37:37.996+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-28T19:37:38.011+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
