[2023-12-28T23:40:22.761+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2023-12-28T23:40:22.770+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2023-12-28T23:40:22.770+0100] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-12-28T23:40:22.783+0100] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): third_task> on 2022-05-02 00:00:00+00:00
[2023-12-28T23:40:22.785+0100] {standard_task_runner.py:57} INFO - Started process 6618 to run task
[2023-12-28T23:40:22.792+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v4', 'third_task', 'scheduled__2022-05-02T00:00:00+00:00', '--job-id', '5448', '--raw', '--subdir', '/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/methode-1/dags/our_first_dag.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmpf1uivpr6']
[2023-12-28T23:40:22.797+0100] {standard_task_runner.py:85} INFO - Job 5448: Subtask third_task
[2023-12-28T23:40:22.853+0100] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v4.third_task scheduled__2022-05-02T00:00:00+00:00 [running]> on host macbook-pro-de-user.local
[2023-12-28T23:40:23.446+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2022-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-02T00:00:00+00:00'
[2023-12-28T23:40:23.448+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2023-12-28T23:40:23.449+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'I am task 3 and I will be running after the task 2!']
[2023-12-28T23:40:23.458+0100] {subprocess.py:86} INFO - Output:
[2023-12-28T23:40:23.460+0100] {subprocess.py:93} INFO - /bin/bash: I: command not found
[2023-12-28T23:40:23.461+0100] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-28T23:40:23.471+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/py_env/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-28T23:40:23.476+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v4, task_id=third_task, execution_date=20220502T000000, start_date=20231228T224022, end_date=20231228T224023
[2023-12-28T23:40:23.487+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 5448 for task third_task (Bash command failed. The command returned a non-zero exit code 127.; 6618)
[2023-12-28T23:40:23.515+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-28T23:40:23.532+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
