[2024-01-01T16:19:17.119+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-01-01T16:19:17.126+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-01-01T16:19:17.126+0100] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2024-01-01T16:19:17.135+0100] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): third_task> on 2023-08-01 00:00:00+00:00
[2024-01-01T16:19:17.138+0100] {standard_task_runner.py:57} INFO - Started process 44384 to run task
[2024-01-01T16:19:17.143+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v4', 'third_task', 'scheduled__2023-08-01T00:00:00+00:00', '--job-id', '12524', '--raw', '--subdir', '/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/methode-1/dags/our_first_dag.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmpxza0kkt0']
[2024-01-01T16:19:17.145+0100] {standard_task_runner.py:85} INFO - Job 12524: Subtask third_task
[2024-01-01T16:19:17.186+0100] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v4.third_task scheduled__2023-08-01T00:00:00+00:00 [running]> on host macbook-pro-de-user.local
[2024-01-01T16:19:17.608+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-01T00:00:00+00:00'
[2024-01-01T16:19:17.609+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2024-01-01T16:19:17.610+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'I am task 3 and I will be running after the task 2!']
[2024-01-01T16:19:17.617+0100] {subprocess.py:86} INFO - Output:
[2024-01-01T16:19:17.619+0100] {subprocess.py:93} INFO - /bin/bash: I: command not found
[2024-01-01T16:19:17.620+0100] {subprocess.py:97} INFO - Command exited with return code 127
[2024-01-01T16:19:17.628+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/py_env/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-01-01T16:19:17.631+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v4, task_id=third_task, execution_date=20230801T000000, start_date=20240101T151917, end_date=20240101T151917
[2024-01-01T16:19:17.639+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 12524 for task third_task (Bash command failed. The command returned a non-zero exit code 127.; 44384)
[2024-01-01T16:19:17.668+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-01T16:19:17.682+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
