[2024-01-01T15:32:58.232+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-05-20T00:00:00+00:00 [queued]>
[2024-01-01T15:32:58.241+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-05-20T00:00:00+00:00 [queued]>
[2024-01-01T15:32:58.242+0100] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2024-01-01T15:32:58.253+0100] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): third_task> on 2023-05-20 00:00:00+00:00
[2024-01-01T15:32:58.256+0100] {standard_task_runner.py:57} INFO - Started process 17574 to run task
[2024-01-01T15:32:58.263+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v4', 'third_task', 'scheduled__2023-05-20T00:00:00+00:00', '--job-id', '11980', '--raw', '--subdir', '/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/methode-1/dags/our_first_dag.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmp_xfsmbj2']
[2024-01-01T15:32:58.266+0100] {standard_task_runner.py:85} INFO - Job 11980: Subtask third_task
[2024-01-01T15:32:58.320+0100] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v4.third_task scheduled__2023-05-20T00:00:00+00:00 [running]> on host macbook-pro-de-user.local
[2024-01-01T15:32:58.859+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-20T00:00:00+00:00'
[2024-01-01T15:32:58.860+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2024-01-01T15:32:58.861+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'I am task 3 and I will be running after the task 2!']
[2024-01-01T15:32:58.869+0100] {subprocess.py:86} INFO - Output:
[2024-01-01T15:32:58.872+0100] {subprocess.py:93} INFO - /bin/bash: I: command not found
[2024-01-01T15:32:58.873+0100] {subprocess.py:97} INFO - Command exited with return code 127
[2024-01-01T15:32:58.883+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/py_env/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-01-01T15:32:58.887+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v4, task_id=third_task, execution_date=20230520T000000, start_date=20240101T143258, end_date=20240101T143258
[2024-01-01T15:32:58.896+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 11980 for task third_task (Bash command failed. The command returned a non-zero exit code 127.; 17574)
[2024-01-01T15:32:58.917+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-01T15:32:58.931+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
